export { default as LoginScreen } from './loginScreen/loginScreen'
export { default as HomeScreen } from './homeScreen/homeScreen'
export { default as RegistrationScreen } from './registrationScreen/registrationScreen'
export { default as FeedScreen } from './feedScreen/feedScreen'
export { default as ProfileScreen } from './profileScreen/profileScreen'
export { default as ContactsScreen } from './contactsScreen/contactsScreen'
